name: Deploy to Frontend
on:
  workflow_dispatch:
  push:
    branches:
      - main
  
permissions: {}

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

env:
  AWS_REGION: "ap-northeast-1"

jobs:
  build_and_deploy:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    environment: Portfolio Production

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run actionlint
        run: |
          set -x
          docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" rhysd/actionlint:1.7.3

      - name: Setup-node
        uses: actions/setup-node@v7 
        with:
          node-version: "24.x"
          cache: "npm"
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build Frontend
        run: npm run build -w packages/frontend
        env:
          VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }}

      - name: Setup AWS cli
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy s3
        run: |
          set -x
          aws s3 sync packages/frontend/dist s3://${{ secrets.AWS_BUCKET }} --delete

      - name: Delete CloudFront cache
        run: |
          set -x
          aws cloudfront create-invalidation \
          --distribution-id ${{ vars.AWS_CLOUDFRONT_DISTRIBUTION_ID }} \
          --path "/*"
